CREATE TABLE "account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"display_name" text NOT NULL,
	"email" text,
	"email_verified" boolean DEFAULT false NOT NULL,
	"role" text DEFAULT 'player' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"claimed_player_id" integer,
	"claimed_bilibili_name" text,
	"bilibili_uid" text,
	"qq_linked" boolean DEFAULT false NOT NULL,
	"preferences" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_role_known" CHECK ("account"."role" IN ('player', 'admin', 'super_admin'))
);
--> statement-breakpoint
CREATE TABLE "auth_identity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_identity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"provider" text NOT NULL,
	"subject" text NOT NULL,
	"secret" text,
	"email" text,
	"email_verified" boolean DEFAULT false NOT NULL,
	"linked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_login_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "email_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "email_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"purpose" text NOT NULL,
	"token_hash" text NOT NULL,
	"email" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"token_hash" text NOT NULL,
	"amr" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_agent" text,
	"ip" text
);
--> statement-breakpoint
CREATE TABLE "campaign" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"cn_name" text,
	"short_name" text NOT NULL,
	"author" text DEFAULT '' NOT NULL,
	"url" text DEFAULT '#' NOT NULL,
	"notice" text,
	"blurb" text DEFAULT '' NOT NULL,
	"banner_key" text,
	"banner_source" text,
	"game_banana_url" text,
	"search_aliases" text[],
	"is_standalone" boolean DEFAULT false NOT NULL,
	"sort_order" integer,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "campaign_hall" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_hall_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"name" text NOT NULL,
	"cn_name" text,
	"aliases" text[],
	"color" text NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_hall_map" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_hall_map_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hall_id" integer NOT NULL,
	"map_id" integer NOT NULL,
	"sort_order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_menu_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campaign_menu_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"section" text NOT NULL,
	"position" integer NOT NULL,
	"campaign_id" integer NOT NULL,
	CONSTRAINT "campaign_menu_item_section_known" CHECK ("campaign_menu_item"."section" IN ('fixed', 'default_favorite')),
	CONSTRAINT "campaign_menu_item_position_nonnegative" CHECK ("campaign_menu_item"."position" >= 0)
);
--> statement-breakpoint
CREATE TABLE "challenge" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "challenge_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope" text NOT NULL,
	"map_id" integer,
	"campaign_id" integer,
	"name" text NOT NULL,
	"type" text,
	"tier_code" text,
	"description" text DEFAULT '' NOT NULL,
	"notice" text,
	"sort_order" integer,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "challenge_scope_shape" CHECK ((
    ("challenge"."scope" = 'map' AND "challenge"."map_id" IS NOT NULL AND "challenge"."campaign_id" IS NULL)
    OR ("challenge"."scope" = 'campaign' AND "challenge"."campaign_id" IS NOT NULL AND "challenge"."map_id" IS NULL)
  )),
	CONSTRAINT "challenge_scope_known" CHECK ("challenge"."scope" IN ('map', 'campaign'))
);
--> statement-breakpoint
CREATE TABLE "challenge_relation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "challenge_relation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"from_id" integer NOT NULL,
	"to_id" integer NOT NULL,
	CONSTRAINT "challenge_relation_not_self" CHECK ("challenge_relation"."from_id" <> "challenge_relation"."to_id")
);
--> statement-breakpoint
CREATE TABLE "challenge_relation_override" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "challenge_relation_override_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"map_id" integer NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "challenge_relation_override_map_id_unique" UNIQUE("map_id")
);
--> statement-breakpoint
CREATE TABLE "map" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "map_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaign_id" integer NOT NULL,
	"name" text NOT NULL,
	"cn_name" text,
	"hist_stars" integer,
	"hist_sub_tier" text,
	"author" text DEFAULT '' NOT NULL,
	"url" text DEFAULT '#' NOT NULL,
	"primary_tier" text,
	"recommendation_percent" integer DEFAULT 0 NOT NULL,
	"rating" integer DEFAULT 0 NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"banner_key" text,
	"banner_source" text,
	"notice" text,
	"search_aliases" text[],
	"sort_order" integer,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "map_hist_rating_valid" CHECK ((
    ("map"."hist_stars" IS NULL AND "map"."hist_sub_tier" IS NULL)
    OR ("map"."hist_stars" IS NOT NULL AND "map"."hist_stars" = 0 AND "map"."hist_sub_tier" IS NULL)
    OR ("map"."hist_stars" IS NOT NULL AND "map"."hist_stars" BETWEEN 1 AND 5
      AND "map"."hist_sub_tier" IS NOT NULL AND "map"."hist_sub_tier" IN ('lower', 'upper'))
  ))
);
--> statement-breakpoint
CREATE TABLE "tier" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"rank" integer NOT NULL,
	"label" text NOT NULL,
	"short" text NOT NULL,
	"is_official" boolean DEFAULT true NOT NULL,
	CONSTRAINT "tier_code_unique" UNIQUE("code"),
	CONSTRAINT "tier_rank_unique" UNIQUE("rank")
);
--> statement-breakpoint
CREATE TABLE "player" (
	"deleted_at" timestamp with time zone,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"bio" text,
	"bilibili_uid" text,
	"bilibili_url" text,
	"bilibili_uids" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"aliases" text[],
	"status" text DEFAULT 'unasked' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "player_avatar_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_avatar_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_id" integer NOT NULL,
	"bilibili_uid" text NOT NULL,
	"object_key" text,
	"fetched_at" timestamp with time zone,
	"attempted_at" timestamp with time zone NOT NULL,
	CONSTRAINT "player_avatar_cache_player_id_unique" UNIQUE("player_id")
);
--> statement-breakpoint
CREATE TABLE "player_binding_code" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_binding_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"player_id" integer,
	"bilibili_uid" text NOT NULL,
	"bilibili_name" text NOT NULL,
	"code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"closed_at" timestamp with time zone,
	"accepted_via" text,
	CONSTRAINT "player_binding_code_format" CHECK ("player_binding_code"."code" ~ '^[A-Z0-9]{4}-[A-Z0-9]{4}$'),
	CONSTRAINT "player_binding_code_method" CHECK ("player_binding_code"."accepted_via" IS NULL OR ("player_binding_code"."accepted_via" IN ('signature', 'admin') AND "player_binding_code"."closed_at" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "player_binding_throttle" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_binding_throttle_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"attempted_at" timestamp with time zone NOT NULL,
	CONSTRAINT "player_binding_throttle_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "player_claim_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_claim_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"bilibili_uid" text NOT NULL,
	"bilibili_name" text NOT NULL,
	"name_source" text DEFAULT 'fetched' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"result_player_id" integer,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"review_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "player_claim_request_status_known" CHECK ("player_claim_request"."status" IN ('pending', 'approved', 'rejected')),
	CONSTRAINT "player_claim_request_source_known" CHECK ("player_claim_request"."name_source" IN ('fetched', 'manual'))
);
--> statement-breakpoint
CREATE TABLE "submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"challenge_id" integer,
	"player_id" integer NOT NULL,
	"submitted_by" integer,
	"status" text DEFAULT 'pending' NOT NULL,
	"achieved_at" date,
	"video_url" text DEFAULT '' NOT NULL,
	"raw_video_url" text,
	"player_note" text,
	"verifier_note" text,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"reviewing_by" integer,
	"reviewing_note" text,
	"reviewing_at" timestamp with time zone,
	"duration" text,
	"opinion_tier" text,
	"recommends" boolean,
	"proposed_target" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "submission_target_shape" CHECK ("submission"."challenge_id" IS NOT NULL OR "submission"."proposed_target" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "submission_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submission_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"submission_id" integer NOT NULL,
	"kind" text NOT NULL,
	"text" text NOT NULL,
	"color" text
);
--> statement-breakpoint
CREATE TABLE "wishlist_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wishlist_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"challenge_id" integer NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"progress" integer DEFAULT 0 NOT NULL,
	"best_deaths" integer,
	"comment" text,
	"practice_duration" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feedback_attachment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_attachment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"report_id" integer,
	"uploader_account_id" integer NOT NULL,
	"object_key" text NOT NULL,
	"content_type" text NOT NULL,
	"bytes" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feedback_report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"page_url" text,
	"reporter" text DEFAULT '' NOT NULL,
	"reporter_account_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"handled_by" integer,
	"handled_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "qa_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qa_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category" text DEFAULT 'general' NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"question_en" text,
	"answer_en" text,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "qa_entry_category" CHECK ("qa_entry"."category" IN ('rules', 'general'))
);
--> statement-breakpoint
CREATE TABLE "suggestion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suggestion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"kind" text NOT NULL,
	"state" text NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"challenge_id" integer,
	"map_id" integer,
	"campaign_id" integer,
	"created_at" text,
	"current_tier" text,
	"suggested_tier" text,
	"result_tier" text,
	"decision" text,
	"decision_note" text,
	"archive_vote_scope" text,
	"archive_votes" jsonb,
	"author" text DEFAULT '' NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"due_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "suggestion_response" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suggestion_response_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"suggestion_id" integer NOT NULL,
	"account_id" integer,
	"player" text NOT NULL,
	"progress" text DEFAULT '' NOT NULL,
	"opinion" text DEFAULT '' NOT NULL,
	"vote" text,
	"opinion_tier" text,
	"comment" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" text NOT NULL,
	"title" text NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"href" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"completed_by" integer,
	"completed_by_label" text
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" text NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"actor" text DEFAULT '系统' NOT NULL,
	"source_key" text
);
--> statement-breakpoint
CREATE TABLE "migration_id_map" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "migration_id_map_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entity" text NOT NULL,
	"old_id" text NOT NULL,
	"new_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trash_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trash_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"target_id" integer NOT NULL,
	"label" text NOT NULL,
	"deleted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trash_item_kind_known" CHECK ("trash_item"."kind" IN ('record', 'campaign', 'map', 'challenge', 'player'))
);
--> statement-breakpoint
CREATE TABLE "trash_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trash_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trash_item_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "image_asset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "image_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"object_key" text NOT NULL,
	"content_type" text NOT NULL,
	"bytes" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "image_asset_object_key_unique" UNIQUE("object_key")
);
--> statement-breakpoint
CREATE TABLE "golden_room_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "golden_room_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rule_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"device_id" integer NOT NULL,
	"player_id" integer NOT NULL,
	"history_epoch" uuid NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "golden_room_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "golden_room_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"map_id" integer NOT NULL,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"room_key" text NOT NULL,
	"room_name" text NOT NULL,
	"extra_text" text DEFAULT '' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "golden_room_rule_side" CHECK ("golden_room_rule"."side" IN ('Normal', 'BSide', 'CSide'))
);
--> statement-breakpoint
CREATE TABLE "golden_room_state" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "golden_room_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rule_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"inside" boolean NOT NULL,
	"history_epoch" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tracker_area_stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_area_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"device_id" integer NOT NULL,
	"dataset_id" uuid NOT NULL,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"completed" boolean,
	"no_golden_best_deaths" integer,
	"total_deaths" integer,
	"source" text DEFAULT 'observed_no_native_golden_clear_v1' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_area_stats_deaths" CHECK ("tracker_area_stats"."no_golden_best_deaths" >= 0),
	CONSTRAINT "tracker_area_stats_total_deaths" CHECK ("tracker_area_stats"."total_deaths" >= 0),
	CONSTRAINT "tracker_area_stats_known_value" CHECK ("tracker_area_stats"."no_golden_best_deaths" IS NOT NULL OR "tracker_area_stats"."total_deaths" IS NOT NULL OR "tracker_area_stats"."completed" IS NOT NULL),
	CONSTRAINT "tracker_area_stats_side" CHECK ("tracker_area_stats"."side" IN ('Normal', 'BSide', 'CSide')),
	CONSTRAINT "tracker_area_stats_source" CHECK ("tracker_area_stats"."source" = 'observed_no_native_golden_clear_v1')
);
--> statement-breakpoint
CREATE TABLE "tracker_cct_room" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_cct_room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope_id" integer NOT NULL,
	"room_key" text NOT NULL,
	"data" jsonb NOT NULL,
	CONSTRAINT "tracker_cct_room_window" CHECK (coalesce(jsonb_typeof("tracker_cct_room"."data"->'previousAttempts') = 'array' AND jsonb_array_length("tracker_cct_room"."data"->'previousAttempts') <= 100, false)),
	CONSTRAINT "tracker_cct_room_key" CHECK (coalesce("tracker_cct_room"."data"->>'roomKey' = "tracker_cct_room"."room_key", false))
);
--> statement-breakpoint
CREATE TABLE "tracker_cct_scope" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_cct_scope_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"device_id" integer NOT NULL,
	"dataset_id" uuid NOT NULL,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"segment_key" text NOT NULL,
	"stream_epoch" uuid NOT NULL,
	"revision" bigint NOT NULL,
	"state_hash" text NOT NULL,
	"last_mutation_id" uuid NOT NULL,
	"last_mutation_hash" text NOT NULL,
	"metadata" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_cct_scope_side" CHECK ("tracker_cct_scope"."side" IN ('Normal', 'BSide', 'CSide')),
	CONSTRAINT "tracker_cct_scope_revision" CHECK ("tracker_cct_scope"."revision" BETWEEN 0 AND 9007199254740991),
	CONSTRAINT "tracker_cct_scope_hash" CHECK ("tracker_cct_scope"."state_hash" ~ '^[a-f0-9]{64}$' AND "tracker_cct_scope"."last_mutation_hash" ~ '^[a-f0-9]{64}$')
);
--> statement-breakpoint
CREATE TABLE "tracker_cct_storage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_cct_storage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"history_epoch" uuid DEFAULT gen_random_uuid() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_cct_storage_account_id_unique" UNIQUE("account_id")
);
--> statement-breakpoint
CREATE TABLE "tracker_device" (
	"external_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_device_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"name" text NOT NULL,
	"client_name" text DEFAULT '' NOT NULL,
	"token_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "tracker_device_external_id_unique" UNIQUE("external_id")
);
--> statement-breakpoint
CREATE TABLE "tracker_device_authorization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_device_authorization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"code_hash" text NOT NULL,
	"code_challenge" text NOT NULL,
	"redirect_uri" text,
	"device_name" text NOT NULL,
	"client_name" text DEFAULT '' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tracker_map_binding" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_map_binding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"map_id" integer NOT NULL,
	"campaign_name" text,
	"chapter_name" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"review_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_map_binding_side" CHECK ("tracker_map_binding"."side" IN ('Normal', 'BSide', 'CSide')),
	CONSTRAINT "tracker_map_binding_status" CHECK ("tracker_map_binding"."status" IN ('pending', 'approved', 'rejected'))
);
--> statement-breakpoint
CREATE TABLE "tracker_map_visit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_map_visit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"device_id" integer NOT NULL,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"history_epoch" uuid NOT NULL,
	"entered_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_map_visit_side" CHECK ("tracker_map_visit"."side" IN ('Normal', 'BSide', 'CSide'))
);
--> statement-breakpoint
CREATE TABLE "tracker_presence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_presence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"connection_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"history_epoch" uuid NOT NULL,
	"sequence" bigint DEFAULT 0 NOT NULL,
	"observation" jsonb,
	"batch_hash" text,
	"connected" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tracker_presence_device_id_unique" UNIQUE("device_id")
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_claimed_player_id_player_id_fk" FOREIGN KEY ("claimed_player_id") REFERENCES "public"."player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_identity" ADD CONSTRAINT "auth_identity_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_token" ADD CONSTRAINT "email_token_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign" ADD CONSTRAINT "campaign_banner_key_image_asset_object_key_fk" FOREIGN KEY ("banner_key") REFERENCES "public"."image_asset"("object_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_hall" ADD CONSTRAINT "campaign_hall_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_hall_map" ADD CONSTRAINT "campaign_hall_map_hall_id_campaign_hall_id_fk" FOREIGN KEY ("hall_id") REFERENCES "public"."campaign_hall"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_hall_map" ADD CONSTRAINT "campaign_hall_map_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_menu_item" ADD CONSTRAINT "campaign_menu_item_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge" ADD CONSTRAINT "challenge_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge" ADD CONSTRAINT "challenge_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge" ADD CONSTRAINT "challenge_tier_code_tier_code_fk" FOREIGN KEY ("tier_code") REFERENCES "public"."tier"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge_relation" ADD CONSTRAINT "challenge_relation_from_id_challenge_id_fk" FOREIGN KEY ("from_id") REFERENCES "public"."challenge"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge_relation" ADD CONSTRAINT "challenge_relation_to_id_challenge_id_fk" FOREIGN KEY ("to_id") REFERENCES "public"."challenge"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge_relation_override" ADD CONSTRAINT "challenge_relation_override_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "challenge_relation_override" ADD CONSTRAINT "challenge_relation_override_updated_by_account_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map" ADD CONSTRAINT "map_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map" ADD CONSTRAINT "map_primary_tier_tier_code_fk" FOREIGN KEY ("primary_tier") REFERENCES "public"."tier"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "map" ADD CONSTRAINT "map_banner_key_image_asset_object_key_fk" FOREIGN KEY ("banner_key") REFERENCES "public"."image_asset"("object_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_avatar_cache" ADD CONSTRAINT "player_avatar_cache_player_id_player_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_avatar_cache" ADD CONSTRAINT "player_avatar_cache_object_key_image_asset_object_key_fk" FOREIGN KEY ("object_key") REFERENCES "public"."image_asset"("object_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_binding_code" ADD CONSTRAINT "player_binding_code_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_binding_code" ADD CONSTRAINT "player_binding_code_player_id_player_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_claim_request" ADD CONSTRAINT "player_claim_request_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_claim_request" ADD CONSTRAINT "player_claim_request_result_player_id_player_id_fk" FOREIGN KEY ("result_player_id") REFERENCES "public"."player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_claim_request" ADD CONSTRAINT "player_claim_request_reviewed_by_account_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_challenge_id_challenge_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenge"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_player_id_player_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_submitted_by_account_id_fk" FOREIGN KEY ("submitted_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_reviewed_by_account_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_reviewing_by_account_id_fk" FOREIGN KEY ("reviewing_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission" ADD CONSTRAINT "submission_opinion_tier_tier_code_fk" FOREIGN KEY ("opinion_tier") REFERENCES "public"."tier"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission_tag" ADD CONSTRAINT "submission_tag_submission_id_submission_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."submission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wishlist_entry" ADD CONSTRAINT "wishlist_entry_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wishlist_entry" ADD CONSTRAINT "wishlist_entry_challenge_id_challenge_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenge"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_attachment" ADD CONSTRAINT "feedback_attachment_report_id_feedback_report_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."feedback_report"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_attachment" ADD CONSTRAINT "feedback_attachment_uploader_account_id_account_id_fk" FOREIGN KEY ("uploader_account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_attachment" ADD CONSTRAINT "feedback_attachment_object_key_image_asset_object_key_fk" FOREIGN KEY ("object_key") REFERENCES "public"."image_asset"("object_key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_report" ADD CONSTRAINT "feedback_report_reporter_account_id_account_id_fk" FOREIGN KEY ("reporter_account_id") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_report" ADD CONSTRAINT "feedback_report_handled_by_account_id_fk" FOREIGN KEY ("handled_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion" ADD CONSTRAINT "suggestion_challenge_id_challenge_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenge"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion" ADD CONSTRAINT "suggestion_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion" ADD CONSTRAINT "suggestion_campaign_id_campaign_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion_response" ADD CONSTRAINT "suggestion_response_suggestion_id_suggestion_id_fk" FOREIGN KEY ("suggestion_id") REFERENCES "public"."suggestion"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggestion_response" ADD CONSTRAINT "suggestion_response_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_task" ADD CONSTRAINT "admin_task_completed_by_account_id_fk" FOREIGN KEY ("completed_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trash_vote" ADD CONSTRAINT "trash_vote_trash_item_id_trash_item_id_fk" FOREIGN KEY ("trash_item_id") REFERENCES "public"."trash_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trash_vote" ADD CONSTRAINT "trash_vote_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD CONSTRAINT "golden_room_event_rule_id_golden_room_rule_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."golden_room_rule"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD CONSTRAINT "golden_room_event_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD CONSTRAINT "golden_room_event_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD CONSTRAINT "golden_room_event_player_id_player_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_rule" ADD CONSTRAINT "golden_room_rule_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_state" ADD CONSTRAINT "golden_room_state_rule_id_golden_room_rule_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."golden_room_rule"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "golden_room_state" ADD CONSTRAINT "golden_room_state_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_area_stats" ADD CONSTRAINT "tracker_area_stats_account_id_tracker_cct_storage_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."tracker_cct_storage"("account_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_cct_room" ADD CONSTRAINT "tracker_cct_room_scope_id_tracker_cct_scope_id_fk" FOREIGN KEY ("scope_id") REFERENCES "public"."tracker_cct_scope"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_cct_scope" ADD CONSTRAINT "tracker_cct_scope_account_id_tracker_cct_storage_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."tracker_cct_storage"("account_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_cct_storage" ADD CONSTRAINT "tracker_cct_storage_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_device" ADD CONSTRAINT "tracker_device_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_device_authorization" ADD CONSTRAINT "tracker_device_authorization_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_map_binding" ADD CONSTRAINT "tracker_map_binding_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_map_binding" ADD CONSTRAINT "tracker_map_binding_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_map_binding" ADD CONSTRAINT "tracker_map_binding_reviewed_by_account_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_map_visit" ADD CONSTRAINT "tracker_map_visit_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_map_visit" ADD CONSTRAINT "tracker_map_visit_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_presence" ADD CONSTRAINT "tracker_presence_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_presence" ADD CONSTRAINT "tracker_presence_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "account_email_lower_key" ON "account" USING btree (lower("email"));--> statement-breakpoint
CREATE UNIQUE INDEX "account_claimed_player_key" ON "account" USING btree ("claimed_player_id");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_identity_provider_subject_key" ON "auth_identity" USING btree ("provider","subject");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_identity_account_provider_key" ON "auth_identity" USING btree ("account_id","provider");--> statement-breakpoint
CREATE UNIQUE INDEX "email_token_hash_key" ON "email_token" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "email_token_account_purpose_idx" ON "email_token" USING btree ("account_id","purpose");--> statement-breakpoint
CREATE UNIQUE INDEX "session_token_hash_key" ON "session" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "session_account_idx" ON "session" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "session_expires_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "campaign_hall_campaign_order_idx" ON "campaign_hall" USING btree ("campaign_id","sort_order");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_hall_map_key" ON "campaign_hall_map" USING btree ("hall_id","map_id");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_hall_map_map_key" ON "campaign_hall_map" USING btree ("map_id");--> statement-breakpoint
CREATE INDEX "campaign_hall_map_order_idx" ON "campaign_hall_map" USING btree ("hall_id","sort_order");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_menu_item_slot_key" ON "campaign_menu_item" USING btree ("section","position");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_menu_item_campaign_key" ON "campaign_menu_item" USING btree ("campaign_id");--> statement-breakpoint
CREATE UNIQUE INDEX "challenge_relation_edge_key" ON "challenge_relation" USING btree ("from_id","to_id");--> statement-breakpoint
CREATE UNIQUE INDEX "player_binding_code_code_key" ON "player_binding_code" USING btree ("code");--> statement-breakpoint
CREATE UNIQUE INDEX "player_binding_code_active_account_key" ON "player_binding_code" USING btree ("account_id") WHERE closed_at IS NULL;--> statement-breakpoint
CREATE INDEX "player_claim_request_status_idx" ON "player_claim_request" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "player_claim_request_pending_account_key" ON "player_claim_request" USING btree ("account_id") WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "submission_challenge_idx" ON "submission" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "submission_player_idx" ON "submission" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "submission_tag_submission_idx" ON "submission_tag" USING btree ("submission_id");--> statement-breakpoint
CREATE UNIQUE INDEX "wishlist_account_challenge_key" ON "wishlist_entry" USING btree ("account_id","challenge_id");--> statement-breakpoint
CREATE INDEX "feedback_attachment_report_idx" ON "feedback_attachment" USING btree ("report_id");--> statement-breakpoint
CREATE INDEX "feedback_attachment_pending_idx" ON "feedback_attachment" USING btree ("uploader_account_id","created_at");--> statement-breakpoint
CREATE INDEX "qa_entry_order_idx" ON "qa_entry" USING btree ("position","created_at");--> statement-breakpoint
CREATE INDEX "suggestion_response_suggestion_idx" ON "suggestion_response" USING btree ("suggestion_id");--> statement-breakpoint
CREATE UNIQUE INDEX "suggestion_response_account_key" ON "suggestion_response" USING btree ("suggestion_id","account_id");--> statement-breakpoint
CREATE INDEX "admin_task_completed_created_idx" ON "admin_task" USING btree ("completed_at","created_at");--> statement-breakpoint
CREATE INDEX "audit_log_at_idx" ON "audit_log" USING btree ("at");--> statement-breakpoint
CREATE UNIQUE INDEX "audit_log_source_key" ON "audit_log" USING btree ("source_key");--> statement-breakpoint
CREATE UNIQUE INDEX "migration_id_map_old_key" ON "migration_id_map" USING btree ("entity","old_id");--> statement-breakpoint
CREATE UNIQUE INDEX "migration_id_map_new_key" ON "migration_id_map" USING btree ("entity","new_id");--> statement-breakpoint
CREATE UNIQUE INDEX "trash_item_target_key" ON "trash_item" USING btree ("kind","target_id");--> statement-breakpoint
CREATE UNIQUE INDEX "trash_vote_item_account_key" ON "trash_vote" USING btree ("trash_item_id","account_id");--> statement-breakpoint
CREATE INDEX "golden_room_event_pending_idx" ON "golden_room_event" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "golden_room_rule_target_key" ON "golden_room_rule" USING btree ("map_id","sid","side","room_key");--> statement-breakpoint
CREATE UNIQUE INDEX "golden_room_state_rule_id_account_id_index" ON "golden_room_state" USING btree ("rule_id","account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_area_stats_owner_key" ON "tracker_area_stats" USING btree ("account_id","device_id","dataset_id","sid","side");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_cct_room_scope_id_room_key_index" ON "tracker_cct_room" USING btree ("scope_id","room_key");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_cct_scope_owner_key" ON "tracker_cct_scope" USING btree ("account_id","device_id","dataset_id","sid","side","segment_key");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_device_token_key" ON "tracker_device" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "tracker_device_account_idx" ON "tracker_device" USING btree ("account_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_device_authorization_code_key" ON "tracker_device_authorization" USING btree ("code_hash");--> statement-breakpoint
CREATE INDEX "tracker_device_authorization_expiry_idx" ON "tracker_device_authorization" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_map_binding_approved_key" ON "tracker_map_binding" USING btree ("sid","side") WHERE status = 'approved';--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_map_binding_pending_key" ON "tracker_map_binding" USING btree ("account_id","sid","side") WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "tracker_map_binding_status_idx" ON "tracker_map_binding" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_map_visit_account_id_device_id_sid_side_index" ON "tracker_map_visit" USING btree ("account_id","device_id","sid","side");--> statement-breakpoint
CREATE INDEX "tracker_presence_account_idx" ON "tracker_presence" USING btree ("account_id");
--> statement-breakpoint
ALTER TABLE "tracker_area_stats" ADD CONSTRAINT "tracker_area_stats_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_cct_scope" ADD CONSTRAINT "tracker_cct_scope_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
INSERT INTO tier (code,rank,label,short,is_official) VALUES
('t-1',0,'Tier -1','T-1',true),
('h0',1,'High Tier 0','High T0',true),
('m0',2,'Mid Tier 0','Mid T0',true),
('l0',3,'Low Tier 0','Low T0',true),
('h1',4,'High Tier 1','High T1',true),
('m1',5,'Mid Tier 1','Mid T1',true),
('l1',6,'Low Tier 1','Low T1',true),
('h2',7,'High Tier 2','High T2',true),
('m2',8,'Mid Tier 2','Mid T2',true),
('l2',9,'Low Tier 2','Low T2',true),
('h3',10,'High Tier 3','High T3',true),
('m3',11,'Mid Tier 3','Mid T3',true),
('l3',12,'Low Tier 3','Low T3',true),
('t4',13,'Tier 4','T4',true),
('t5',14,'Tier 5','T5',true),
('t6',15,'Tier 6','T6',true),
('t7',16,'Tier 7','T7',true),
('high-std',17,'High Std','High Std',false),
('mid-std',18,'Mid Std','Mid Std',false),
('low-std',19,'Low Std','Low Std',false),
('undetermined',20,'未定档','未定档',false);
