CREATE TABLE "daily_summary_delivery" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_summary_delivery_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"summary_date" date NOT NULL,
	"group_id" text NOT NULL,
	"status" text DEFAULT 'claimed' NOT NULL,
	"claimed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"message_id" text,
	CONSTRAINT "daily_summary_delivery_status_known" CHECK ("daily_summary_delivery"."status" IN ('claimed', 'sent', 'failed'))
);
--> statement-breakpoint
ALTER TABLE "submission" ADD COLUMN "accepted_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX "daily_summary_delivery_date_group_key" ON "daily_summary_delivery" USING btree ("summary_date","group_id");--> statement-breakpoint
CREATE INDEX "submission_accepted_at_idx" ON "submission" USING btree ("accepted_at");
--> statement-breakpoint
-- 旧数据缺少独立通过时间，只能按审核时间、其次创建时间回填。
UPDATE submission SET accepted_at = coalesce(reviewed_at, created_at) WHERE status = 'accepted';
--> statement-breakpoint
CREATE FUNCTION maintain_submission_accepted_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.accepted_at := CASE WHEN NEW.status = 'accepted' THEN statement_timestamp() ELSE NULL END;
  ELSIF NEW.status = 'accepted' AND OLD.status IS DISTINCT FROM 'accepted' THEN
    NEW.accepted_at := statement_timestamp();
  ELSE
    NEW.accepted_at := OLD.accepted_at;
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER submission_accepted_at_trigger BEFORE INSERT OR UPDATE ON submission
FOR EACH ROW EXECUTE FUNCTION maintain_submission_accepted_at();
