CREATE TABLE "tracker_challenge_selection" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_challenge_selection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" integer NOT NULL,
	"map_id" integer NOT NULL,
	"challenge_id" integer NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD COLUMN "challenge_id" integer;--> statement-breakpoint
ALTER TABLE "tracker_challenge_selection" ADD CONSTRAINT "tracker_challenge_selection_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_challenge_selection" ADD CONSTRAINT "tracker_challenge_selection_map_id_map_id_fk" FOREIGN KEY ("map_id") REFERENCES "public"."map"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_challenge_selection" ADD CONSTRAINT "tracker_challenge_selection_challenge_id_challenge_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenge"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "tracker_challenge_selection_account_id_map_id_index" ON "tracker_challenge_selection" USING btree ("account_id","map_id");--> statement-breakpoint
ALTER TABLE "golden_room_event" ADD CONSTRAINT "golden_room_event_challenge_id_challenge_id_fk" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenge"("id") ON DELETE set null ON UPDATE no action;