CREATE TABLE "tracker_shared_route" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracker_shared_route_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"external_id" uuid NOT NULL,
	"account_id" integer NOT NULL,
	"device_id" integer,
	"sid" text NOT NULL,
	"side" text NOT NULL,
	"name" text NOT NULL,
	"revision" bigint NOT NULL,
	"content_hash" text NOT NULL,
	"payload" jsonb,
	"payload_bytes" integer NOT NULL,
	"room_count" integer NOT NULL,
	"source_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "tracker_shared_route_external_id_unique" UNIQUE("external_id"),
	CONSTRAINT "tracker_shared_route_side_check" CHECK ("tracker_shared_route"."side" IN ('Normal','BSide','CSide')),
	CONSTRAINT "tracker_shared_route_revision_check" CHECK ("tracker_shared_route"."revision" > 0),
	CONSTRAINT "tracker_shared_route_payload_bytes_check" CHECK ("tracker_shared_route"."payload_bytes" >= 0 AND "tracker_shared_route"."payload_bytes" <= 8388608),
	CONSTRAINT "tracker_shared_route_room_count_check" CHECK ("tracker_shared_route"."room_count" >= 0 AND "tracker_shared_route"."room_count" <= 2000)
);
--> statement-breakpoint
ALTER TABLE "tracker_shared_route" ADD CONSTRAINT "tracker_shared_route_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_shared_route" ADD CONSTRAINT "tracker_shared_route_device_id_tracker_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."tracker_device"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_shared_route" ADD CONSTRAINT "tracker_shared_route_source_id_tracker_shared_route_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."tracker_shared_route"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tracker_shared_route_map_idx" ON "tracker_shared_route" USING btree ("sid","side","updated_at","id");--> statement-breakpoint
CREATE INDEX "tracker_shared_route_account_idx" ON "tracker_shared_route" USING btree ("account_id");