/** 从只读源库快照导入空新库，保留映射；默认整笔回滚预览。 */
import { readFileSync } from "node:fs";
import { Pool, type PoolClient } from "pg";
import { pool } from "../../src/db/client";
import { getConfig } from "../../src/config";
import { checkDatabase } from "./check";

type Row = Record<string, unknown>;
type Column = { column_name: string; data_type: string; is_nullable: string; column_default: string | null; is_identity: string };
type Foreign = { column_name: string; foreign_table: string; foreign_column: string };
type Asset = { objectKey: string; contentType: string; bytes: number };
type Manifest = Record<string, Asset>;
const quote = (name: string) => '"'+name.replaceAll('"','""')+'"';
function remapValue(maps: Map<string, Map<string, number>>, table: string, old: unknown) {
  if (old === null || old === undefined) return null;
  const id = maps.get(table)?.get(String(old));
  if (id === undefined) throw new Error(`缺少 ${table} 的旧 ID 映射`);
  return id;
}
export async function importSource(source: PoolClient, target: PoolClient, options: { apply?: boolean; assets?: Manifest } = {}) {
  const sourceTables = (await source.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")).rows.map(r=>r.table_name as string);
  const targetTables = (await target.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")).rows.map(r=>r.table_name as string).filter(t=>t!=="migration_id_map");
  const columns = new Map<string, Column[]>(), sourceColumns = new Map<string, Set<string>>(), foreign = new Map<string, Foreign[]>();
  for (const table of targetTables) {
    columns.set(table,(await target.query("SELECT column_name,data_type,is_nullable,column_default,is_identity FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position",[table])).rows);
    sourceColumns.set(table,new Set((await source.query("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",[table])).rows.map(r=>r.column_name)));
    foreign.set(table,(await target.query(`SELECT a.attname AS column_name, ft.relname AS foreign_table, fa.attname AS foreign_column
      FROM pg_constraint c JOIN pg_class t ON t.oid=c.conrelid JOIN pg_class ft ON ft.oid=c.confrelid
      JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=c.conkey[1]
      JOIN pg_attribute fa ON fa.attrelid=ft.oid AND fa.attnum=c.confkey[1]
      WHERE c.contype='f' AND t.relnamespace='public'::regnamespace AND t.relname=$1`,[table])).rows);
  }
  const counts: Record<string, number> = {}, maps = new Map<string, Map<string, number>>();
  for (const table of [...targetTables,"migration_id_map"]) {
    if (table === "tier") continue;
    const count=Number((await target.query(`SELECT count(*) AS n FROM ${quote(table)}`)).rows[0].n);
    if (count) throw new Error(`目标库 ${table} 非空；不允许覆盖或重复导入`);
  }
  const sourceTiers=(await source.query("SELECT code,rank,is_official FROM tier ORDER BY rank")).rows;
  const targetTiers=(await target.query("SELECT code,rank,is_official FROM tier ORDER BY rank")).rows;
  if(JSON.stringify(sourceTiers)!==JSON.stringify(targetTiers)) throw new Error("源库 Tier 字典与当前业务规则不一致，须先核对");
  for(const table of targetTables.filter(t=>t!=="tier" && sourceColumns.get(t)?.has("id"))) {
    const ids=(await source.query(`SELECT id FROM ${quote(table)} ORDER BY id::text COLLATE "C"`)).rows;
    maps.set(table,new Map(ids.map((r,i)=>[String(r.id),i+1])));
  }
  // New surrogate IDs on relationship tables are generated by the target database.
  const order: string[]=[]; const pending=new Set(targetTables.filter(t=>t!=="tier"));
  while(pending.size) {
    const next=[...pending].find(t=>(foreign.get(t)??[]).every(f=>!pending.has(f.foreign_table) || f.foreign_table===t));
    if(!next)throw new Error("表依赖存在未处理的循环");
    pending.delete(next);order.push(next);
  }
  const assetValues = new Map<string, Asset>();
  for(const asset of Object.values(options.assets??{})) {
    if(!asset.objectKey || asset.objectKey.startsWith("/") || asset.objectKey.split("/").some(p=>p===".." || !p) || !/^image\/(jpeg|png|gif|webp)$/.test(asset.contentType) || !Number.isSafeInteger(asset.bytes) || asset.bytes<1) throw new Error("图片索引清单格式无效");
    assetValues.set(asset.objectKey,asset);
  }
  if(sourceTables.includes("feedback_attachment")) for(const r of (await source.query("SELECT object_key,content_type,bytes FROM feedback_attachment")).rows) {
    assetValues.set(r.object_key,{objectKey:r.object_key,contentType:r.content_type,bytes:r.bytes});
  }
  for(const asset of assetValues.values())await target.query("INSERT INTO image_asset(object_key,content_type,bytes) VALUES($1,$2,$3)",[asset.objectKey,asset.contentType,asset.bytes]);
  const assetKey=(old:unknown,required:boolean)=>{
    if(!old)return null;
    const found=options.assets?.[String(old)];
    if(found)return found.objectKey;
    if(required)throw new Error("存在未迁移的封面；请先提供 --assets 图片索引清单");
    return null;
  };
  const routeId=(value:unknown)=> {
    if(typeof value!=="string")return value;
    const routeTables: Record<string,string>={campaign:"campaign",campaigns:"campaign",map:"map",maps:"map",challenge:"challenge",challenges:"challenge",player:"player",players:"player",submission:"submission",submissions:"submission",record:"submission",records:"submission",suggestions:"suggestion"};
    return value.replace(/\/(campaigns?|maps?|challenges?|players?|submissions?|records?|suggestions)\/([^/?#]+)/g,(full,route,old)=>{
      const mapped=maps.get(routeTables[route])?.get(decodeURIComponent(old));return mapped ? `/${route}/${mapped}` : full;
    });
  };
  for(const table of order) {
    if(table==="image_asset"){counts[table]=assetValues.size;continue;}
    if(!sourceTables.includes(table)) {counts[table]=0;continue;}
    const data=(await source.query(`SELECT * FROM ${quote(table)}`)).rows as Row[];
    counts[table]=data.length;
    const cols=columns.get(table)!;
    for(const old of data) {
      const row:Row={};
      for(const col of cols) {
        const name=col.column_name;
        if(name==="id") {if(sourceColumns.get(table)!.has("id"))row.id=remapValue(maps,table,old.id);continue;}
        if(table==="tracker_device"&&name==="external_id"){row[name]=old.id;continue;}
        if((table==="campaign"||table==="map")&&name==="banner_key"){row[name]=assetKey(old.banner,true);continue;}
        if(table==="player_avatar_cache"&&name==="object_key"){row[name]=assetKey(old.url,false);continue;}
        if(table==="player_avatar_cache"&&name==="fetched_at"&&!options.assets?.[String(old.url)]){row[name]=null;continue;}
        if(table==="campaign"&&name==="notice"){row[name]=old.blurb||null;continue;}
        if(!(name in old))continue;
        let value=old[name];
        const fk=foreign.get(table)?.find(f=>f.column_name===name);
        if(fk?.foreign_column==="id")value=remapValue(maps,fk.foreign_table,value);
        // Natural keys reference a numeric parent column with a uniqueness constraint.
        if(name==="account_id"&&fk?.foreign_table==="tracker_cct_storage")value=remapValue(maps,"account",old[name]);
        if(name==="device_id"&&!fk)value=remapValue(maps,"tracker_device",old[name]);
        if(table==="trash_item"&&name==="target_id")value=remapValue(maps,old.kind==="record"?"submission":String(old.kind),value);
        if(table==="account"&&name==="preferences"&&value&&typeof value==="object") {
          const prefs={...value} as Row;
          if(Array.isArray(prefs.favoriteCampaignIds))prefs.favoriteCampaignIds=prefs.favoriteCampaignIds.map(id=>remapValue(maps,"campaign",id));
          value=prefs;
        }
        if(name==="href"||name==="page_url")value=routeId(value);
        row[name]=value;
      }
      const names=Object.keys(row);
      const values=names.map(name=>{
        const c=cols.find(c=>c.column_name===name)!;const value=row[name];
        return value!==null && (c.data_type==="jsonb"||c.data_type==="json") ? JSON.stringify(value) : value;
      });
      await target.query(`INSERT INTO ${quote(table)}(${names.map(quote).join(',')}) VALUES(${names.map((_,i)=>'$'+(i+1)).join(',')})`,values);
    }
  }
  for(const [entity,mapping]of maps)for(const [oldId,newId]of mapping)await target.query("INSERT INTO migration_id_map(entity,old_id,new_id) VALUES($1,$2,$3)",[entity,oldId,newId]);
  for(const table of targetTables)await target.query(`SELECT setval(pg_get_serial_sequence($1,'id'), GREATEST(COALESCE(MAX(id),0),1), COUNT(*)>0) FROM ${quote(table)}`,[table]);
  await checkDatabase(target);
  return { dryRun: !options.apply, counts, mappedEntities: Object.fromEntries([...maps].map(([k,v])=>[k,v.size])) };
}

if(process.argv[1]?.endsWith("import-source.ts")) {
  const arg=(name:string)=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1];};
  const sourceConfigPath=arg("--source-config");
  let sourcePool:Pool|undefined,source:PoolClient|undefined,target:PoolClient|undefined;
  try {
    if(!sourceConfigPath)throw new Error("用法：npm run db:import-source -- --source-config source.local.json [--assets assets.json] [--apply]");
    const sourceConfig=JSON.parse(readFileSync(sourceConfigPath,"utf8"));
    const sourceUrl=sourceConfig.database?.url;
    if(typeof sourceUrl!=="string")throw new Error("源配置缺少 database.url");
    const a=new URL(sourceUrl),b=new URL(getConfig().database.url);
    if(a.hostname===b.hostname && (a.port||"5432")===(b.port||"5432") && a.pathname===b.pathname)throw new Error("源库与目标库不能相同");
    sourcePool=new Pool({connectionString:sourceUrl,max:1});source=await sourcePool.connect();target=await pool.connect();
    const sourceIdentity=await source.query("SELECT current_database() AS db,inet_server_addr()::text AS host,inet_server_port() AS port");
    const targetIdentity=await target.query("SELECT current_database() AS db,inet_server_addr()::text AS host,inet_server_port() AS port");
    if(JSON.stringify(sourceIdentity.rows)===JSON.stringify(targetIdentity.rows))throw new Error("源库与目标库实际为同一数据库");
    await source.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");await target.query("BEGIN");
    const file=arg("--assets");const apply=process.argv.includes("--apply");
    const result=await importSource(source,target,{apply,assets:file?JSON.parse(readFileSync(file,"utf8")):undefined});
    await target.query(apply?"COMMIT":"ROLLBACK");await source.query("ROLLBACK");console.log(JSON.stringify(result,null,2));
  } catch(error) { await target?.query("ROLLBACK").catch(()=>undefined);await source?.query("ROLLBACK").catch(()=>undefined);console.error(error instanceof Error?error.message:"Migration failed");process.exitCode=1; }
  finally {source?.release();target?.release();await sourcePool?.end();await pool.end();}
}
